NoteApp/NoteApp.WebUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NoteApp.Data.Abstract;
using NoteApp.Data.Concrete;
using NoteApp.Data.Concrete.EfCore;
using NoteApp.Entity;
using NoteApp.WebUI.Data;
using Newtonsoft.Json;

namespace NoteApp.Controllers
{
    public class HomeController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Note n)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var userName = User.Identity.Name;
            var noterepository = new EfCoreNoteRepository();
            Note newnote = new Note
            {
                NoteId = n.NoteId,
                Name = n.Name,
                Description = n.Description,
                ImgUrl = n.ImgUrl,
                Username = userName,
                UserId = userId
            };
            noterepository.Create(newnote);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Delete(int NoteId)
        {
            var noterepository = new EfCoreNoteRepository();
            noterepository.Delete(noterepository.GetById(NoteId));
            return RedirectToAction("Index");
        }

        public IActionResult Publish(int id)
        {
            var noterepository = new EfCoreNoteRepository();
            noterepository.DoPublish(id);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Media()
        {
            var notes = new List<Note>();

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:4200/api/publishednotes"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    notes = JsonConvert.DeserializeObject<List<Note>>(apiResponse);
                }
            }

            return View(notes);
        }
    }
}

NoteApp/NoteApp.WebUI/ViewComponents/NotesViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NoteApp.Business.Abstract;
using NoteApp.Data;
using NoteApp.Data.Abstract;
using NoteApp.Entity;
using NoteApp.WebUI.Models;

namespace NoteApp.ViewComponents
{
    public class NotesViewComponent : ViewComponent
    {
        private INoteService _noteService;

        public NotesViewComponent(INoteService noteService)
        {
            this._noteService = noteService;
        }
        public IViewComponentResult Invoke()
        {
            var userId = UserClaimsPrincipal.FindFirstValue(ClaimTypes.NameIdentifier);
            return View(_noteService.GetByUserId(userId));
        }
    }
}

NoteApp/NoteApp.WebUI/Views/Home/Index.cshtml
@{
    Layout = "_Layout";
}

@await Html.PartialAsync("_navbar")
<main class="container p-5 mx-auto" style="min-height: 817px;">
    @await Component.InvokeAsync("Notes")
    @await Html.PartialAsync("_createbutton")
    @await Html.PartialAsync("_createmodal")
</main>
@await Html.PartialAsync("_footer")

NoteApp/NoteApp.WebUI/Views/Home/Media.cshtml
@model List<Note>
<!doctype html>
<html lang="en">

<head>
    <title>Media</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/6de428ecbe.js" crossorigin="anonymous"></script>
</head>
<style>
    * {
        margin: 0px;
        padding: 0px;
    }

    .note {
        border: 1px solid #343a40;
        border-radius: 20px;
        font-size: 18px;
        cursor: pointer;
        transition: all .5s ease;
    }

    .note a {
        color: #343a40;
        text-decoration: none;
    }

    .note a:hover {
        opacity: .5;
        transition: all .5s ease;
    }

    .note span:hover {
        opacity: .5;
        transition: all .5s ease;
    }

    .createbutton {
        text-align: center;
        border-radius: 20px !important;
        font-size: 18px !important;
    }

    footer {
        text-align: center;
    }
</style>

<body>

    @await Html.PartialAsync("_navbar")
    <main class="container p-5 mx-auto" style="min-height: 817px;">
        @foreach (var note in Model)
        {
            <div class="note m-3 row mx-auto p-3">
                <span class="col-md-11 col-10">@note.Username / @note.Name</span>
                <a href="@note.ImgUrl" onclick="openImg(this)" class="fa-solid fa-eye col-md-1 col-2 fa-ms"></a>
            </div>
        }
    </main>
    @await Html.PartialAsync("_footer")

    <script>
        function openImg(element) {
            var href = element.href;
            var win = window.open();
            win.document.write('<iframe src="' + href + '" frameborder="0" style="border:0; top:0px; left:0px; bottom:0px; right:0px; width:100%; height:100%;" allowfullscreen></iframe>');
        }
    </script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

NoteApp/NoteApp.WebUI/Views/Home/_Layout.cshtml
@model Note
<!doctype html>
<html lang="tr">

<head>
    <title>Note Blocks</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/6de428ecbe.js" crossorigin="anonymous"></script>
</head>

<style>
    * {
        margin: 0px;
        padding: 0px;
    }

    .note {
        border: 1px solid #343a40;
        border-radius: 20px;
        font-size: 18px;
        cursor: pointer;
        transition: all .5s ease;
    }

    .note a {
        color: #343a40;
        text-decoration: none;
    }

    .note a:hover {
        opacity: .5;
        transition: all .5s ease;
    }

    .note span:hover {
        opacity: .5;
        transition: all .5s ease;
    }

    .createbutton {
        text-align: center;
        border-radius: 20px !important;
        font-size: 18px !important;
    }

    footer {
        text-align: center;
    }
</style>

<body>

    @RenderBody()

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
</body>

</html>

NoteApp/NoteApp.WebUI/Views/Home/_alert.cshtml
@model List<Note>

@if (@Model.Count == 0)
{
    <div class="alert alert-danger" style="border-radius: 20px !important;">
        You don't have any note
    </div>
}

NoteApp/NoteApp.WebUI/Views/Home/_createbutton.cshtml
<button type="button" class="btn btn-dark bg-dark w-100 p-3 createbutton" data-toggle="modal"
    data-target="#exampleModal">
    + Create a new note
</button>

NoteApp/NoteApp.WebUI/Views/Home/_createmodal.cshtml
@model Note
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create Note</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST">
                    <div class="form-group">
                        <label for="exampleInputName">Name</label>
                        <input asp-for="Name" class="form-control" aria-describedby="nameHelp" placeholder="Enter name"
                            minlength="1" maxlength="16">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlTextarea1">Description</label>
                        <textarea class="form-control" asp-for="Description" rows="3"></textarea>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-dark">Save changes</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

NoteApp/NoteApp.WebUI/Views/Home/_footer.cshtml
<footer class="bg-dark text-white">
    <div class="container mx-auto p-3">
        <span>Tüm Hakları Saklıdır - Ege Yapıcı</span>
    </div>
</footer>

NoteApp/NoteApp.WebUI/Views/Home/_navbar.cshtml
<nav class="navbar navbar-dark navbar-expand-sm bg-dark">
    <div class="container mx-auto">
        <a href="/home/index" class="navbar-brand">Note Blocks</a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a href="/home/media" class="nav-link mx-2">Media</a>
            </li>
            <li class="nav-item">
                <a href="/sign/logout" class="nav-link mx-2">Logout</a>
            </li>
        </ul>
    </div>
</nav>